name: workflow to trigger wallmart us
on:
  push:
    branches:
      - wmtu

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: 12
          run: yarn install
        - name: Push build to S3
          uses: sai-sharan/aws-s3-sync-action@master